const connection = require('./db/connection')
const express = require('express')
const app = express()
const adminOsRoute = require('./modules/mobile/routers/OsRouter/OsRouter')
const adminVersionRouter = require('./modules/mobile/routers/version_router/OsVersionRouter')
const BrandRouter = require('./modules/mobile/routers/BrandRouter/BrandRouter')
const ModelRouter = require('./modules/mobile/routers/modelRoute/modelRoute')
const adminSpecificationCategoryRouter = require('./modules/mobile/routers/specificationCategoryRouter/specificationCategoryRouter')
const adminFeatureRouter = require('./modules/mobile/routers/FeatureRouter/featureRouter')
const userDetailsRoute = require('./modules/userPanel/routers/userRouter')
const productRoute = require('./modules/mobile/routers/productRouter/productRouter')
const featureDetail = require('./modules/mobile/routers/featureDetails/featureDetails')
const addressRouter = require('./modules/userPanel/routers/addressRouter')
const orderRouter = require('./modules/orders/routers/orderrouter')

app.use(express.json())
app.use(adminOsRoute)
app.use(adminVersionRouter)
app.use(BrandRouter)
app.use(ModelRouter)
app.use(adminSpecificationCategoryRouter)
app.use(adminFeatureRouter)
app.use(userDetailsRoute)
app.use(productRoute)
app.use(featureDetail)
app.use(addressRouter)
app.use(orderRouter)


app.listen(4000,()=>{
    console.log("Connected to localhost:4000")
})